services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./task_management_app/frontend:/app  # Изменяем путь сюда
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./task_management_app/backend:/app  # Изменяем путь сюда
    command: sh -c "sleep 10 && pip install -r requirements.txt && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/app_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: